version: '3.8'
services:
  frontend:
    container_name: frontend_react_app
    build: ./frontend
    image: ghcr.io/ehn7/devops-project-backend:latest
    ports:
      - '80:80'
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 'eduardo'
      MYSQL_DATABASE: 'my_to_do_list'
    ports:
    - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    container_name: backend_flask_app
    build: ./backend
    image: ghcr.io/ehn7/devops-project-backend:latest
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: 'db'
      DB_USER: 'root'
      DB_PASSWORD: 'eduardo'
      DB_NAME: 'my_to_do_list'
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data: